// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmwbpjcprskbazdibdkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptd2JwamNwcnNrYmF6ZGliZGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTgxMjEsImV4cCI6MjA3MjM3NDEyMX0.ik-1TRHIhOUJZZo1UZ4D0WmvYD9GFOWFgLXjMMe8X1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});